# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 02:14


from django.db import migrations
from django.contrib.auth.models import User
from spider.driver.travel.core.traveldriver import WEBSITE_NAME_LIST,DATASOURCE_NAME_LIST,DATAREGION_NAME_LIST

def InitTravelDataBase(apps, schema_editor):
    #创建超级管理员
    User.objects.create_superuser('root', 'root@root.com', '12345678')
    #往数据库添加初始化数据
    model_data_list = [{"app_name":"spider","model_name":"DataWebsite","data_list":WEBSITE_NAME_LIST},{"app_name":"spider","model_name":"DataRegion","data_list":DATAREGION_NAME_LIST},{"app_name":"spider","model_name":"DataSource","data_list":DATASOURCE_NAME_LIST}]
    for i in model_data_list:
        print(i.get('model_name'))
        model = apps.get_model(i.get('app_name'), i.get('model_name'))
        db_alias = schema_editor.connection.alias
        data_list = []
        for data in i.get('data_list'):
            data_list.append(model(name=data))
            print(data)
        model.objects.using(db_alias).bulk_create(data_list)

class Migration(migrations.Migration):
    dependencies = [
        ('spider', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(InitTravelDataBase),
    ]