# Generated by Django 2.0.6 on 2018-07-10 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRegion',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='景区')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='数据类型')),
            ],
        ),
        migrations.CreateModel(
            name='DataWebsite',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='网站来源')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='stop', editable=False, max_length=10, verbose_name='项目状态')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='首次创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('data_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.DataRegion')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.DataSource')),
                ('data_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.DataWebsite')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('data_website', 'data_region', 'data_source')},
        ),
    ]
