# Generated by Django 2.0.5 on 2018-05-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', 'spider_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
